name: "Setup"
description: "Setup Bun, install dependencies, and optionally install Playwright browsers"

inputs:
  install-playwright:
    description: "Whether to install Playwright browsers"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          node_modules
          client/node_modules
          api/node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --frozen-lockfile

    - name: Cache Playwright browsers
      if: inputs.install-playwright == 'true'
      uses: actions/cache@v4
      id: cache-playwright
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('client/package.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true' && steps.cache-playwright.outputs.cache-hit != 'true'
      shell: bash
      run: bunx playwright@1.58.2 install --with-deps chromium

    - name: Install Playwright deps (OS libraries)
      if: inputs.install-playwright == 'true' && steps.cache-playwright.outputs.cache-hit == 'true'
      shell: bash
      run: bunx playwright@1.58.2 install-deps chromium
