export const LIMITS = {
  ACTIVITY_NAME_MAX: 50,
  CATEGORY_NAME_MAX: 50,
  SUBCATEGORY_NAME_MAX: 50,
  DESCRIPTION_MAX: 1000,
  MAX_ACTIVITIES_PER_USER: 20000,
  MAX_CATEGORIES_PER_USER: 100,
  MAX_SUBCATEGORIES_PER_CATEGORY: 50,
} as const;

export const RATE_LIMIT = {
  REQUESTS_PER_MINUTE: 60,
  WINDOW_MS: 60 * 1000,
} as const;
