const ACTIVITY_NAME_MAX = 50;

export const LIMITS = {
  ACTIVITY_NAME_MAX,
  CATEGORY_NAME_MAX: 50,
  ACTIVITY_NAME_IN_CATEGORY_MAX: ACTIVITY_NAME_MAX,
  DESCRIPTION_MAX: 1000,
  MAX_ACTIVITIES_PER_USER: 20000,
  MAX_CATEGORIES_PER_USER: 100,
  MAX_ACTIVITY_NAMES_PER_CATEGORY: 50,
  MAX_TIME_SPENT: 1440,
} as const;

export const RATE_LIMIT = {
  REQUESTS_PER_MINUTE: 60,
  WINDOW_MS: 60 * 1000,
} as const;
