/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated.index";
import { Route as AuthenticatedActivityListRouteImport } from "./routes/_authenticated.activity-list";
import { Route as AuthenticatedChartsRouteImport } from "./routes/_authenticated.charts";
import { Route as AuthenticatedCompareRouteImport } from "./routes/_authenticated.compare";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated.settings";
import { Route as AuthenticatedWelcomeRouteImport } from "./routes/_authenticated.welcome";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedActivityListRoute =
  AuthenticatedActivityListRouteImport.update({
    id: "/activity-list",
    path: "/activity-list",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: "/charts",
  path: "/charts",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute;
  "/login": typeof LoginRoute;
  "/activity-list": typeof AuthenticatedActivityListRoute;
  "/charts": typeof AuthenticatedChartsRoute;
  "/compare": typeof AuthenticatedCompareRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/welcome": typeof AuthenticatedWelcomeRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/activity-list": typeof AuthenticatedActivityListRoute;
  "/charts": typeof AuthenticatedChartsRoute;
  "/compare": typeof AuthenticatedCompareRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/welcome": typeof AuthenticatedWelcomeRoute;
  "/": typeof AuthenticatedIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/activity-list": typeof AuthenticatedActivityListRoute;
  "/_authenticated/charts": typeof AuthenticatedChartsRoute;
  "/_authenticated/compare": typeof AuthenticatedCompareRoute;
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute;
  "/_authenticated/welcome": typeof AuthenticatedWelcomeRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/activity-list"
    | "/charts"
    | "/compare"
    | "/settings"
    | "/welcome";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/activity-list"
    | "/charts"
    | "/compare"
    | "/settings"
    | "/welcome"
    | "/";
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/activity-list"
    | "/_authenticated/charts"
    | "/_authenticated/compare"
    | "/_authenticated/settings"
    | "/_authenticated/welcome"
    | "/_authenticated/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/activity-list": {
      id: "/_authenticated/activity-list";
      path: "/activity-list";
      fullPath: "/activity-list";
      preLoaderRoute: typeof AuthenticatedActivityListRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/charts": {
      id: "/_authenticated/charts";
      path: "/charts";
      fullPath: "/charts";
      preLoaderRoute: typeof AuthenticatedChartsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/compare": {
      id: "/_authenticated/compare";
      path: "/compare";
      fullPath: "/compare";
      preLoaderRoute: typeof AuthenticatedCompareRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/welcome": {
      id: "/_authenticated/welcome";
      path: "/welcome";
      fullPath: "/welcome";
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityListRoute: typeof AuthenticatedActivityListRoute;
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute;
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute;
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityListRoute: AuthenticatedActivityListRoute,
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
