name: "Bundlewatch"

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@v2.1.0
      - run: yarn && yarn run download-config ${{ secrets.CLIENT_CONFIG_URL }} && yarn run build
      - run: npx bundlewatch
