name: "Bundlewatch"

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install
        run: bun install
      - name: build client
        run: bun run download-config ${{ secrets.CLIENT_CONFIG_URL }} && bun run build
        working-directory: client
      - name: bundlewatch
        run: bun run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
