name: "Depcheck"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: depcheck
        run: bun install && bun run depcheck
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body-path: scripts/depcheck-report.md
